"""empty message

Revision ID: 25db88e19627
Revises: 776f3846006c
Create Date: 2025-01-05 18:21:59.596267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25db88e19627'
down_revision = '776f3846006c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('resume', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
